### PR TITLE
Implemented HDFS as an InputAdapter

### PR DESCRIPTION
**Pull request by JamesDavidCarr**
This is based off of the Kafka InputAdapter implementation.

Depending on the size and number of files stored on HDFS this implementation may change.

### CODE REVIEW

**Comment by JamesDavidCarr** [comment]
> What happens if the file is longer than 1 page?

https://github.com/lsds/SEEPng/pull/3/files#diff-281113af027e02be2d48bf263641b34aR125 handles this case by reading from the input stream as long as there are bytes to read. The input stream is just an abstraction for the file being read from here.

> Also, I'm pretty sure IBuffer.pushData is actually supposed to take the bytes for a single ITuple, not just a generic bunch of bytes.

I'll look into this now. I did base this integration off of the [KafkaSelector](https://github.com/lsds/SEEPng/blob/master/seep-contrib/src/main/java/uk/ac/imperial/lsds/seepcontrib/kafka/comm/KafkaSelector.java#L108) which simply reads from the Kafka iterator and pushes bytes out. If I find that this is incorrect, I'll change both.

**Comment by WJCIV** [comment]
It looks to me like the Kafka client is receiving messages which already encapsulate single records. You might get some inspiration from the Reader in FileSelector.java. It's probably a little closer to this as it reads chunks of data from a file and splits it into records itself.

EDIT: Looks like you've already got a handle on this. For some reason my browser wasn't showing the latest commit before this comment.

**Comment by WJCIV** [comment]
The latest version looks promising. I'll run some tests on Monday.

Do you have time to take a look at selecting between text and binary input? What you have now should work for binary. There has been a new text option added since you started this ( https://github.com/raulcf/SEEPng/pull/58/files ). You would need to add a new boolean (binary or text input) and string (charset name) to the config. Aside from that I think you can pull the isTextSource and  readFromText functions from FileSelector with minimal alteration.

**Comment by JamesDavidCarr** [comment]
I tested against a local hdfs installation to make sure that everything is working and I'm pretty confident with the code.

The reader now assumes a path that can either be a file or a directory (possibly containing subdirectories) of files to read from.

**Comment by WJCIV** [comment]
Getting close. From what I can tell there's just one link in the chain missing. Your tests as written directly access some of the internals, but we provide a "source" and "sink" abstraction for users. Somehow you need to connect HDFS capabilities to a source and sink. The easiest way would be to create a new source (HDFSSource). A more elegant solution might extend the functionality of FileSource, since files on HDFS are files.

Right now we should be able to use your HDFS code to transfer data between operators, but I'm not seeing a clean way to use it for initial input.

**Comment by raulcf** [comment]
Have not looked into the impl. yet. However, I think we can piggyback the FileSource class, only giving a hdfs:// URL. Unles I'm missing something important here...

HDFSConfig will implement FileConfig, so that we can configure both a plain file and one in HDFS.

**Comment by JamesDavidCarr** [comment]
This integration was initially so that I could gain some experience of working in the SEEP codebase, but it's taken a lot of my time recently and I really need to spend more time working on my actual project.

I'd really appreciate if someone could lay out clearly the remaining steps of the integration so that I can finish this up as soon as possible.

**Comment by raulcf** [comment]
Sure!
The integration of any external data source with SEEP consists of 2 steps (same case in Spark, Flink, an pretty much any DB):

1- Write the business logic that understand how to access data from the source and write it into the system/framework/db. (I understand this is done)
2- Provide a means for users to choose the external store and configure it if necessary.

I understand you've done 1, 2 should be straightforward. In particular, I was proposing before that you can probably reuse FileSource. @WJCIV can help here, this should be pretty quick.

**Comment by WJCIV** [comment]
If you take a look in the example folder you can see how users actually interface with the system. The basic idea is to create a set of tasks which process input and turn it into output. So if you have one operation which processes the data you define the input (source), the task, and the output (sink), then the connections between them. If you have two operations the flow is source -> task 1 -> task 2 -> sink where the output from task 1 placed in a Dataset and used as input to task 2.

Your code can read data from HDFS and place it in a Dataset, but that is one step shy of creating the source abstraction the user can actually use. Without this a user cannot say say that the initial Dataset for a job resides in HDFS.

The options are:
1. Create an HDFSSource. This is probably easier, although likely not by much.
2. Add a configuration to FileConfig (used by FileSource) that marks it as residing on HDFS and update the FileSource to use your new code when this is marked. While this might be a bit more complex it will be much easier for users to understand (a file is a file, regardless of which file system is used) and will allow them to move to HDFS with a simple configuration setting instead of replacing their source classes.

I'd recommend you look at the Base class in the simple-sourcefile-stateless-query example to see how a user actually programs source -> task -> sink.

**Comment by JamesDavidCarr** [comment]
Thanks very much for the comments. I'll have this finished by the end of the weekend.

**Comment by WJCIV** [comment]
Do you have a status update?

**Comment by WJCIV** [comment]
Is there any chance this will be completed by tomorrow?

**Comment by JamesDavidCarr** [comment]
Hi @WJCIV, very sorry that I haven't gotten back sooner.

I'm in the middle of exam revision time and have had to put all other work
on hold for now before I'll be able to continue working on this.

I finish on the 21st March and after that will be allocating all of my time
to working on finishing this implementation.

Thank you for your patience.

**Comment by WJCIV** [comment]
https://github.com/raulcf/SEEPng/pull/68 -- We're working on integrating HDFS directly into existing sources rather than creating new sources to make it easier on potential users. I had to refactor your code a bit to get this to work, so it's on a separate branch.

**Comment by raulcf** [comment]
I think one can ask for a FileSource and then provide two types of uris:
file://<path>
or
hdfs://<path>
is this what you mean?

**Pull request closed without merging**
